name: MLOps Docker CI

on:
  push:
    branches:
      - docker_ci

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install scikit-learn joblib

      - name: Run training script
        run: python src/train.py

      - name: Build Docker image
        run: docker build -t saiswaroopkakarla/mlops-pipeline:latest .

      - name: Run Docker container
        run: docker run saiswaroopkakarla/mlops-pipeline:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push saiswaroopkakarla/mlops-pipeline:latest

